p1 = input("Digite o nome do produto 1:")
v1 = float(input("Digite o preço do produto 1:"))
q1 = int(input("Digite a quantidade do produto 1:"))
p2 = input("Digite o nome do produto 2:")
v2 = float(input("Digite o preço do produto 2:"))
q2 = int(input("Digite a quantidade do produto 2:"))
p3 = input("Digite o nome do produto 3:")
v3 = float(input("Digite o preço do produto 3:"))
q3 = int(input("Digite a quantidade do produto 3:"))
Saida = (q1 * v1) + (q2 * v2) + (q3 * v3)
print(f"Total: R${Saida:,.2f}")